### PR TITLE
:children_crossing: Adding negative argument to list_lsm()

### PR DESCRIPTION
**Pull request by mhesselbarth**
For example `list_lsm(level = "patch", negative = TRUE)` gives all **BUT** patch level metrics.

### CODE REVIEW

**Comment by Nowosad** [comment]
@mhesselbarth It is a nice functionality. I am just curious if it would be possible (and make any sense) to implement it in different way - with a minus sign? E.g.:

```r
list_lsm(level = "-patch")
```

**Comment by mhesselbarth** [comment]
Give me 5 minutes, I'm working on it right now :)

**Comment by mhesselbarth** [comment]
Alrigt...with the help of @marcosci we came up with the current solutions. The advantage to the previous one is that negative and positive subsets can be combined now, e.g. `list_lsm(level = "class", type = "-aggregation metric", metric = "-cai")` giving you all class level metrics with exception of aggregation metrics and the core area index.

**Comment by Nowosad** [comment]
Magic.

**Pull request merged**
