### PR TITLE
Simplify cooccurence rcpp

### PR DESCRIPTION
**Pull request by marcosci**
So ...

@bitbacchus and I made some slight changes:

rcpp_get_coocurrence now loops over the input data, which is faster and does not allocate new memory.
This also means that we don't need get_pairs and get_adjacency anymore - I deleted them.
Or do you see any reasoning keeping them?

I also restructured the src folder a bit, we should maybe think about creating subfolders there in the way @Nowosad organized the initial files: adjacency script, ... 

While implementing the new coocurrence function, we also found a new function for `unique` that is insanely fast - if you like it, we could exchange every unique in the package with it (there is an rcpp function already in `/src`.

This should fix the issues in #52 and make the branch `rcpp_fix` obsolete.

### CODE REVIEW

**Comment by Nowosad** [comment]
Hi guys! It looks like a great work.
However, where can I find the `rcpp_get_coocurrence_matrix2()` function? I want to try and compare the old and the new function?

**Comment by marcosci** [comment]
It's called like your function now, without the 2.

**Comment by Nowosad** [comment]
So the old function does not exist anymore?

**Comment by marcosci** [comment]
Not in this branch... Wasn't maybe that clever 😅

**Comment by Nowosad** [comment]
I just want to test timings on medium sized data using both functions. Tests are not failing - so maybe that's not a huge problem.

**Comment by marcosci** [comment]
I put the previous version of the function in this branch, at the end of `TEMP_old_adjacency.cpp` you will also find a benchmark comparing the versions. The api is exactly the same, it seems like it also returns the same numbers for every raster I tested there. Here are some results:

```r
> bench::mark(
+     new = rcpp_get_coocurrence_matrix(mat, four),
+     old = rcpp_get_coocurrence_matrix_old(mat, four),
+     iterations = 1000,
+     check = TRUE,
+     relative = TRUE
+ )
# A tibble: 2 x 14
  expression   min  mean median   max `itr/sec` mem_alloc  n_gc n_itr total_time result          memory              time     gc                  
  <chr>      <dbl> <dbl>  <dbl> <dbl>     <dbl>     <dbl> <dbl> <dbl>      <dbl> <list>          <list>              <list>   <list>              
1 new         1     1      1      1        7.92        1    NaN     1       1    <int [15 × 15]> <Rprofmem [2 × 3]>  <bch:tm> <tibble [1,000 × 3]>
2 old         7.56  7.92   7.60  13.0      1       15689.   Inf     1       7.92 <int [15 × 15]> <Rprofmem [13 × 3]> <bch:tm> <tibble [1,000 × 3]>
```

**Comment by marcosci** [comment]
There is now also a new `lsm_p_contig`, which should be way faster than the old and do not use as much memory as the previous one.

**Comment by marcosci** [comment]
Sure, will do during the day :+1: 
I also think that we can use this now as a first building block for the surfacemetrics package :tada:

**Comment by Nowosad** [comment]
Definitely. We can also think about the possibility of separating the building blocks (e.g. cpp code) from the landscapemetrics package and put it into some helper package.

**Comment by marcosci** [comment]
That would make sense at some point :+1:

**Comment by Nowosad** [comment]
Oh, and I've got a new idea while traveling to my office - have you tried comparing the performance of **landscapemetrics** to FRAGSTATS? It could show where are we doing good and where there is a place for improvement. This could also be, together with handling big files, a nice advertising point.

**Comment by marcosci** [comment]
How would you benchmark a GUI? :thinking:

**Comment by mhesselbarth** [comment]
Also, FRAGSTATS is ridiculously fast...

**Comment by bitbacchus** [comment]
@Nowosad , I'm glad you like it :-)

> 1. Can you add some comments to the cpp code? It would be helpful for us in the future

Marco wrote 2 lines of comment, not sure if that's already enough documentation. Do you see any parts in the code that are especially unintuitive and need some clarifying?

> 2. Can you write some short summary what have you changed? It could help for people with the same problem as ours in the future.

The major point is to avoid Armadillo ;-) The point is that any Rcpp-objects are directly mapped to the actual R-objects, i.e. they do not need any additional memory. Creating arma::imat (or any other data structure) from the Rcpp object effectively doubles the memory consumption and slows down everything because allocating this much memory takes much time. Converting it back to Rcpp consumes the same amount of memory, again. 

A minor thing is to find a way to access the Rcpp object directly with the []-operator and avoid function calls () in the innermost loop.

Best, Sebastian

**Comment by Nowosad** [comment]
> @Nowosad , I'm glad you like it :-)
> 
> > 1. Can you add some comments to the cpp code? It would be helpful for us in the future
> 
> Marco wrote 2 lines of comment, not sure if that's already enough documentation. Do you see any parts in the code that are especially unintuitive and need some clarifying?
> 
> > 1. Can you write some short summary what have you changed? It could help for people with the same problem as ours in the future.
> 
> The major point is to avoid Armadillo ;-) The point is that any Rcpp-objects are directly mapped to the actual R-objects, i.e. they do not need any additional memory, if they already exist in R. Creating arma::imat (or any other data structure) from the Rcpp object effectively doubles the memory consumption and slows down everything because allocating this much memory takes much time. Converting it back to Rcpp consumes the same amount of memory, again.
> 
> A minor thing is to find a way to access the Rcpp object directly with the []-operator and avoid function calls () in the innermost loop.
> 
> Best, Sebastian

Hey @bitbacchus - thanks for the explanation. I've learned a lot here!

**Pull request merged**
