### PR TITLE
rewrite construct_buffer

### PR DESCRIPTION
**Pull request by Nowosad**
@mhesselbarth take a look at this approach. I think (but not 100% certain) that's the proper solution. Take a look at it and merge if you think it is fine. 
BTW - tests still need to be written.

### CODE REVIEW

**Comment by marcosci** [comment]
The problem with your approach would be that sf becomes a dependency - as enhance it would not be one. That's also the reason for the weird **stars** handling.

**Comment by Nowosad** [comment]
Quote from Hadley: "Enhances: packages listed here are “enhanced” by your package. Typically, this means you provide methods for classes defined in another package (a sort of reverse Suggests)". I think that exactly what I am doing here...

**Comment by mhesselbarth** [comment]
Your approach is definitely cleaner than mine, but I agree with @marcosci - the idea was to avoid including sf as a dependency (which would be necessaire for your approach).

**Comment by Nowosad** [comment]
https://cran.r-project.org/doc/manuals/R-exts.html#Creating-R-packages 

"Finally, the ‘Enhances’ field lists packages “enhanced” by the package at hand, e.g., by providing methods for classes from these packages, or ways to handle objects from these packages (so several packages have ‘Enhances: chron’ because they can handle datetime objects from chron even though they prefer R’s native datetime functions). Version requirements can be specified, but are currently not used. Such packages cannot be required to check the package: any tests which use them must be conditional on the presence of the package. (If your tests use e.g. a dataset from another package it should be in ‘Suggests’ and not ‘Enhances’.) "

**Comment by marcosci** [comment]
Ah - I think we tried it with stars and did something wrong. Just gave it a second spin and using stars there worked for me and did not result in a warning. So we should go for your solution :+1:

**Pull request merged**
