### PR TITLE
Rcpp updates

### PR DESCRIPTION
**Pull request by bitbacchus**
Hi,

this probably needs some additional testing and tidy-up (e.g. I left the old get_boundary function in to enable comparisons). Could you have a look, so we can merge?

### CODE REVIEW

**Comment by bitbacchus** [comment]
Hi, thanks for reviewing, so far!

>> There is also an inconsistency for directions = 8:

> I think the argument is now called rooks_case = TRUE/FALSE, right?

Yes, in C++ 0 is false and any number greater than 0 is true, so '8' is actually casted to a rooks_case = TRUE. Maybe this is confusing, shall we change it to 4/8 instead?

> However, benchmarking on my laptop, get_boundaries2() is slightly slower than get_boundaries() for larger rasters (not for landscape though). 

Hm, I get quite the oppisite results:

```R
class_11 <- landscapemetrics::get_patches(landscapemetrics::augusta_nlcd, 
                                         class = 11)[[1]]

class_11_mat <- raster::as.matrix(class_1)

bench::mark(
    a = landscapemetrics:::get_boundaries(class_11_mat),
    b = landscapemetrics:::get_boundaries2(class_11_mat), 
    iterations = 1000
)

# A tibble: 2 x 14
expression      min     mean   median     max `itr/sec` mem_alloc      
    a            2.47ms   2.87ms   2.66ms  5.49ms      348.     6.9MB 
    b          600.64µs 871.39µs 696.73µs  2.17ms     1148.    2.29MB
```
I would guess, the differences grow bigger, the larger the matrix, because some rbind/cbind operations are done in C++ and they are very slow for large matrices in R. Actually, I think the core edge detection algorithm is not much faster than in the raster-code, but the pre- and postprocessing (padding) of the matrix are now done in C++.

**Comment by bitbacchus** [comment]
Oh, and could you please also check the new get_unique_values.R function? Especially whether it works with different raster* objects?

**Comment by bitbacchus** [comment]
> Thanks for the explanation @mhesselbarth. Let me know if you need any help with adding documentation/tests.

I'd appreciate if you could write one or two tests! 

The documentation shouldn't change if I'm not mistaken? 

Another thing we should do before merging is to add some sanity checks to the R-functions to assure, the users do not pass the wrong data types to C++.

**Comment by mhesselbarth** [comment]
> Hm, I get quite the oppisite results:
> 
> ```r
> class_11 <- landscapemetrics::get_patches(landscapemetrics::augusta_nlcd, 
>                                          class = 11)[[1]]
> 
> class_11_mat <- raster::as.matrix(class_1)
> 
> bench::mark(
>     a = landscapemetrics:::get_boundaries(class_11_mat),
>     b = landscapemetrics:::get_boundaries2(class_11_mat), 
>     iterations = 1000
> )
> 
> # A tibble: 2 x 14
> expression      min     mean   median     max `itr/sec` mem_alloc      
>     a            2.47ms   2.87ms   2.66ms  5.49ms      348.     6.9MB 
>     b          600.64µs 871.39µs 696.73µs  2.17ms     1148.    2.29MB
> ```
> 
> I would guess, the differences grow bigger, the larger the matrix, because some rbind/cbind operations are done in C++ and they are very slow for large matrices in R. Actually, I think the core edge detection algorithm is not much faster than in the raster-code, but the pre- and postprocessing (padding) of the matrix are now done in C++.

I don't want to be a smart-ass but you are still using `class_1` (probably from `landscape`) and not `class_11` (from `augusta_nlcd`) in your benchmark...

**Comment by bitbacchus** [comment]
> I don't want to be a smart-ass but you are still using class_1 (probably from landscape) and not class_11 (from augusta_nlcd) in your benchmark...

No, I just wanted to make the code look prettier here on GitHub and forgot to change that variable name. I just shouldn't do such things at 11:15 pm...

```R
class_11 <- landscapemetrics::get_patches(landscapemetrics::augusta_nlcd, 
                                         class = 11)[[1]]

class_11_mat <- raster::as.matrix(class_11)

bench::mark(
    a = landscapemetrics:::get_boundaries(class_11_mat),
    b = landscapemetrics:::get_boundaries2(class_11_mat), 
    iterations = 1000
)

# A tibble: 2 x 14
expression      min     mean   median     max `itr/sec` mem_alloc      
    a            2.89ms   3.23ms   2.98ms  14.39ms      310.    6.93MB 
    b          667.96µs 730.65µs  692.8µs   1.64ms     1369.     2.3MB
```

**Comment by mhesselbarth** [comment]
Well...that's odd. Anyway, I would say we use your new `Rcpp` function no matter what. Seems to be faster on most laptops. Additionally, we have the chance to change the function every time we are not happy with it. 

I actually added some functionality to the `R` wrapper this morning and re-coded everything that your new stuff is used through the package.

**Comment by marcosci** [comment]
A bit late to the party, but Sebastians new function is also slower for smaller raster on my machine and on the cloud servers :man_shrugging: 

```r
class_1 <- landscapemetrics::get_patches(landscapemetrics::landscape, 
                                          class = 1)[[1]]

class_11 <- landscapemetrics::get_patches(landscapemetrics::augusta_nlcd, 
                                          class = 11)[[1]]

class_1_mat <- raster::as.matrix(class_1)
class_11_mat <- raster::as.matrix(class_11)

bench::mark(
    a = landscapemetrics:::get_boundaries_old(class_1_mat),
    b = landscapemetrics:::get_boundaries(class_1_mat), 
    c = landscapemetrics:::get_boundaries_old(class_11_mat),
    d = landscapemetrics:::get_boundaries(class_11_mat), 
    iterations = 1000,
    check = FALSE
)

# A tibble: 4 x 14
  expression      min     mean   median      max `itr/sec` mem_alloc  n_gc n_itr total_time
  <chr>      <bch:tm> <bch:tm> <bch:tm> <bch:tm>     <dbl> <bch:byt> <dbl> <int>   <bch:tm>
1 a           29.48µs  36.71µs  35.62µs 114.85µs    27243.   23.55KB     1   999    36.67ms
2 b           61.61µs  67.06µs  65.31µs 147.81µs    14911.   10.98KB     0  1000    67.06ms
3 c            2.66ms   3.28ms   3.12ms   7.35ms      305.     6.9MB   156   844      2.77s
4 d          649.69µs 774.48µs 726.57µs   1.63ms     1291.    2.29MB    52   948    734.2ms
```

If the padding works better in Rcpp, shouldn't we use that than also in pad_raster?

**Comment by marcosci** [comment]
c and d are augusta, hence my comment for smaller raster :relaxed:

Sounds good to me, should also soon start to brainstorm for a good structure for the src folder (maybe on gitter).

**Comment by marcosci** [comment]
We should :yum:

**Comment by mhesselbarth** [comment]
> 
> 
> We should 😋

Done: db084ac7

**Pull request merged**
