### PR TITLE
adds scale_lsm

### PR DESCRIPTION
**Pull request by Nowosad**
``` r
library(landscapemetrics)
library(ggplot2)
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.3.2, PROJ 5.2.0
library(raster)
#> Loading required package: sp

data("augusta_nlcd")
augusta_nlcd2 = raster(augusta_nlcd)
augusta_nlcd2[] = augusta_nlcd[]

new_point = st_sf(geom = st_sfc(
    st_point(c(1265000, 1250000)),
    st_point(c(1255000, 1257000))))

plot(augusta_nlcd2)
plot(new_point, add = TRUE)
```

``` r

my_points = st_coordinates(new_point)

result = scale_lsm(augusta_nlcd, my_points, buffer_width = 500, max_width = 5000,
                   what = c("lsm_l_ent", "lsm_l_mutinf"))
#> Warning: Some of buffers extend over the landscape border. Consider
#> decreasing of the max_width argument value.

ggplot(result, aes(size, value)) +
    geom_line() + 
    facet_grid(metric~plot_id)
```

<sup>Created on 2019-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### CODE REVIEW

**Comment by Nowosad** [comment]
Hi all,
I've added a new function - `scale_lsm()`. It still probably needs some polishing, etc., but I would be great if you can take a look at it.
I plan to add some tests after your comments.

Three things:
1. I've added a warning when the percentage of a calculated area is lower than 99% of the buffer area. I do not know if this the best approach.
2. @mhesselbarth I found out that `sample_lsm()` accepts a size argument of length larger than 1. I think there should be an error when the user set this argument to a vector of length larger than 1.
3. Maybe it is a good idea to add a accompanying plot function here

**Comment by marcosci** [comment]
Looks fab Jakub!

Should the plot function look like the share plots?

**Comment by Nowosad** [comment]
I think it could be a little bit different. Maybe something like the figure below for one raster and `facet_wrap(layer~metric)` for rasterstack/brick, etc...

``` r
library(landscapemetrics)
library(ggplot2)
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.3.2, PROJ 5.2.0
library(raster)
#> Loading required package: sp

data("augusta_nlcd")
augusta_nlcd2 = raster(augusta_nlcd)
augusta_nlcd2[] = augusta_nlcd[]

new_point = st_sf(geom = st_sfc(
    st_point(c(1265000, 1250000)),
    st_point(c(1255000, 1257000))))

my_points = st_coordinates(new_point)

result = scale_lsm(augusta_nlcd, my_points, buffer_width = 500, max_width = 5000,
                   what = c("lsm_l_ent", "lsm_l_mutinf"))
#> Warning: Some of buffers extend over the landscape border. Consider
#> decreasing of the max_width argument value.

ggplot(result, aes(size, value, color = as.factor(plot_id), group = as.factor(plot_id))) +
    geom_line() + 
    facet_wrap(~metric)
```



<sup>Created on 2019-06-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Nowosad** [comment]
This could be useful - https://ggplot2.tidyverse.org/dev/articles/ggplot2-in-packages.html

**Comment by mhesselbarth** [comment]
The function looks really good - great idea! I had a look at it and there were some minor issues I fixed.

1. I changed the buffer_width/buffer_max arguments to size/size_max to be consistent to `sample_lsm()`.
2. Also, now it's possible to select the same shapes as for `sample_lsm()`.
3. The idea to return a warning if `percentage_inside` is below a certain threshold is great, but I think there was a bug. I set the threshold to 75%, but feel free to change it to whatever you think is appropriate.
4. The results are only ordered by  `order(layer, plot_id, level, metric, class, id, size)` now and not by the `value` or the `percentage_inside` (I think this is highly confusing).

Just merge the pull request if the changes are ok for you!

P.S. I will have a look at `sample_lsm()`

**Comment by marcosci** [comment]
I renamed scale_lsm to scale_sample (as discussed with Max, if @Nowosad has a better name - please go for it).

Furthermore, we came up with scale_window - a new function that takes given percentages of a landscape for a moving window size, calculates lsm and then summarizes them by descriptive statistics (`raster::cellStats`). The idea basically imitates a cumulative point pattern statistic. A next step could be to have a non-cumulative version of that, so looking at landscape patterns in a moving _ring_ around focal cells (see concept of a pair-correlation function for point patterns).

Any thoughts on that Jakub?

Anyways, for the plotting: Both functions have nearly the same output in means of how to visualize them, so we should go for one single functions, maybe `show_scales`.

**Comment by Nowosad** [comment]
@mhesselbarth @marcosci Good ideas. 


>     1. I changed the buffer_width/buffer_max arguments to size/size_max to be consistent to `sample_lsm()`.

@marcosci How about making it consistent to the landscapetools package?

>     3. The idea to return a warning if `percentage_inside` is below a certain threshold is great, but I think there was a bug. I set the threshold to 75%, but feel free to change it to whatever you think is appropriate.

@mhesselbarth I cannot think right now of a better way to find the situation of going outside of the data extent. However, I would set the threshold to some larger value (90%?).

**Comment by marcosci** [comment]
I played around with plotting function for both functions and couldn't come up with a reasonable solution - as users could use so many sampling locations, metrics, etc. 
If none of you has a good idea how to deal with this in a very concise way, I would vote for no plotting function here.

**Comment by Nowosad** [comment]
Great work @marcosci and @mhesselbarth. Are there any tests related to this new functions?

**Comment by mhesselbarth** [comment]
Yes, I just added them today: 4727d3c9 and 19ca66bc, however, the test for `scale_window()` will be skipped on CRAN and CIs because the function is quite slow at the moment.

**Pull request merged**
