### PR TITLE
Adds terra support

### PR DESCRIPTION
**Pull request by Nowosad**
In the same vain as **stars** - it uses `Enhances` and does not automatically test.

### CODE REVIEW

**Comment by mhesselbarth** [comment]
Travis CI seems to fail, but not sure if that's an issue on their side and some servers are down?

**Comment by Nowosad** [comment]
Servers were down. I rebooted travis and it worked fine.

**Comment by mhesselbarth** [comment]
Perfect! Awesome job BTW

**Comment by Nowosad** [comment]
Feel free to merge it.

**Pull request merged**
