### PR TITLE
Update v1.1

### PR DESCRIPTION
**Pull request by mhesselbarth**

### CODE REVIEW

**Comment by mhesselbarth** [comment]
@marcosci @Nowosad 
 
If you agree, I would update the CRAN version to v1.1 within the next days.

**Comment by Nowosad** [comment]
I will take a look tomorrow. (My suggestion is to update the CRAN version sometime next week - to have at least one month difference between CRAN submissions...)

**Comment by mhesselbarth** [comment]
That was my schedule as well, great! I hope I’ll get the missing stars support fixed tomorrow. Then we have some time to double check everything next week.

**Comment by Nowosad** [comment]
Great changes @mhesselbarth !

**Pull request merged**
