### PR TITLE
New circle implementation

### PR DESCRIPTION
**Pull request by bitbacchus**
This is my attempt to address the T-shaped patch problem. ~~Btw, should we open a bug for this - for transparency reasons?~~ There is also a bug report #164 

There have quite some other things changed, too. 
## value
`rcpp_get_circle` returns now a data.frame with the following content:
- patch_id
- ~~patch_area~~
- patch_height
- patch_width
- circle_area
- circle_center
- circle_radius

The additional values a calculated anyways. As this is an internal function, we can also return everything useful and ignore the stuff we don't need.

## landscape matrix instead of points as input
`rcpp_get_circle` handles all pointy bits internally, now.

## Only a single resolution argument
I think different resolutions in x and y directions probably make no sense in this context. This would likely mess up the calculations, and I don't know how to calculate circle areas when the radius in the x-direction is different from the radius in the y-direction. I suggest that we check and throw in error in all *_circle* functions if the raster* object has not the same x and y resolution.

## patches with only one cell, not zero anymore
For some reason, one-cell patches where set zero in `lsm_p_circle`. This makes no sense, IMHO. Each cell has an area and four corner points. It can be circumscribed by a circle perfectly well. 

## ~30% faster with `lsm_p_circle(landscape)`
Faster is always better, right ;-)

## Todo
- [x] the new version is considerably different from the original measure. We need to discuss this.
- [x] I messed in quite some R files around. Someone needs to have a look there :-)
- [x] allow real numbers as resolution
- [x] remove patch area measurement

### CODE REVIEW

**Comment by Nowosad** [comment]
Hi @bitbacchus , it would be great if you could open a new issue and explain the problem briefly (I have no idea what's the T-shaped patch problem).

**Comment by bitbacchus** [comment]
> Hi @bitbacchus , it would be great if you could open a new issue and explain the problem briefly (I have no idea what's the T-shaped patch problem).

So true :+1:  -> #165

**Comment by bitbacchus** [comment]
Oh, and just FYI: 

I used external code for the actual algorithm ([link](https://www.nayuki.io/page/smallest-enclosing-circle)), with some cosmetic changes. It is GPL 3, and the author kindly asks to get informed if s/o uses his code. I'm going to do this when we merge his code.

I believe the used algorithm is Welzl's algorithm, but I'll check this.

**Comment by mhesselbarth** [comment]
I had a look at the code. Overall, very nice work @bitbacchus! 

I just see a few small issues with the code as it is right now: 

1) CIRCLE = 0 for patches with only one cell is based on the FRAGSTATS manual. Since there is no explanation of why they define this special case, I'm okay with handling this differently. Maybe their idea was that one cell is the closest you get to a circle in the raster context? @Nowosad  Do you see why this could be defined this way?

2) If we do all the "pointy bits" inside the C++ function there is some redundancy in the code right now (once we decided on how to do this, I can take care of that). However, I don't like the idea to calculate the area within the C++ function. As far as I understand the code, this needs to be done anyway, but we decided in the past to use always the lowest-level (i.e. patch level) lsm-function, so in case we need to change/fix something there always is just one place to do so, 

3) Because the resolution is a `<const unsigned>`, there is a problem with rasters that have a resolution < 0, e.g. rasters with a degree CSR as  `podlasie_ccilc`.

4) For all other metrics, we allow rasters with different x-y resolutions. I agree that this is not very common, but I definitely have seen such rasters from time to time. As far as I understand the code, this shouldn't be super hard to also allow here, correct?

**Comment by mhesselbarth** [comment]
Oh...and 5) 😄 

You used a new method to get the boundary cells of each patch, correct? We already have `rcpp_get_boundaries` which does the same I guess. Maybe makes also sense to get the two consistent in this case.

**Comment by bitbacchus** [comment]
> 1. CIRCLE = 0 ...

This would make sense if a raster cell is not defined by its four corners but rather its center point, imho

> 2. If we do all the "pointy bits" inside the C++ function there is some redundancy in the code right ...

I already tried to remove it as long it was obvious to me... This definitely needs some more checks :+1: 

> 3. Because the resolution is a <const unsigned>, there is a problem with rasters that have a resolution < 0, e.g. rasters with a degree CSR as podlasie_ccilc.

Oh, ok. I didn't know that's a possibility.

> 4. For all other metrics, we allow rasters with different x-y resolutions. I agree that this is not very common, but I definitely have seen such rasters from time to time. As far as I understand the code, this shouldn't be super hard to also allow here, correct?

Well, by definition, a circle is an infinite number of points, all at the same distance from the center. If we allow different resolutions in x and y direction, this becomes not trivial, at least. We'd need to generalize the algorithm for ellipses which sounds complicated...

>  5. You used a new method to get the boundary cells of each patch, correct? 

No, only the points that are minimum or maximum are used. We do not need boundary points that are not either max(x), max(y), min(x) or min(y).

**Comment by bitbacchus** [comment]
Oh, and
> 3 a. However, I don't like the idea to calculate the area within the C++ function. As far as I understand the code, this needs to be done anyway, but we decided in the past to use always the lowest-level (i.e. patch level) lsm-function, so in case we need to change/fix something there always is just one place to do so,

The area is not actually needed, but trivially to measure "on-the-fly". it just saves a call of lsm_p_area. But as both should not be performace critical, I'd agree to remove this for cleaner code.

**Comment by mhesselbarth** [comment]
Okay...we fixed some stuff: 

1) A patch with only once cell now has a circle related to it (We didn't know why FRAGSTATS sets this case to CIRCLE = 0 and couldn't come up with an explanation)
2) We use `lsm_p_area` to calculate the area during `lsm_p_circle
3) The resolution does not have to be an integer
4) lsm_p_circle returns an error if the resolution is not identical in x- and y-direction. It would be quite complicated to allow this. So for the moment, we decided to implement the error. We can think about this more if somebody requests it.
5) `get_circumscribingcircle` has a better structure now and the option to select `level = "patch"`or `level = "class"`

**Comment by bitbacchus** [comment]
This seems to work quite nicely, already. 

However, we lose the data from the raster's extent. `rcpp_get_circle` assumes that the origin of the coordinate system is in the bottom-left corner. When I calculate the circles from a raster where (0, 0) is somewhere else, the circle coordinates get all messy:

```R
x 

class      : RasterLayer 
dimensions : 1001, 1001, 1002001  (nrow, ncol, ncell)
resolution : 1, 1  (x, y)
extent     : -500.5, 500.5, -500.5, 500.5  (xmin, xmax, ymin, ymax)
crs        : NA 
source     : memory
names      : state 
values     : 0, 3  (min, max)

landscapemetrics::get_circumscribingcircle(x) 

# A tibble: 5,085 x 7
   layer level class    id value center_x center_y
   <int> <chr> <int> <int> <dbl>    <dbl>    <dbl>
 1     1 patch     0     1  5.10     0.5      962.
 2     1 patch     0     2  5.83     1.5      928.
 3     1 patch     0     3  5.15     1.62     868 
 4     1 patch     0     4  3.16     0.5      844.
 5     1 patch     0     5  5.83     1.5      832.
 6     1 patch     0     6  5.10     0.5      814.
 7     1 patch     0     7  5.10     0.5      768.
 8     1 patch     0     8  5.83     1.5      750.
 9     1 patch     0     9  5.83     2.5      734.
10     1 patch     0    10  2.24     0.5      638 
# … with 5,075 more rows
```

**Comment by bitbacchus** [comment]
I fixed the issue with the extent and also added the case that there is no resolution. However, there is no method for "matrix" implemented. Is this for a reason or by accident?

**Comment by mhesselbarth** [comment]
This is for a reason as it is an advantage of the package: 

> "Additionally, the use of raster data has advantages in having all required spatial information included and eliminating possible error sources, such as a misspecified cell size. "

**Comment by mhesselbarth** [comment]
Are we sure we do not run into any problems during the circle diameter calculations due to CRS?

**Pull request merged**
