### PR TITLE
Fix cclabel

### PR DESCRIPTION
**Pull request by bitbacchus**
We have now something to discuss (see f9c1fb2). What do you think?

### CODE REVIEW

**Comment by Nowosad** [comment]
hi @bitbacchus , I think we could replace the old function with the new ones. However, I would suggest to test it first my comparing results (and times) of the cclabel functions with `rcpp_ccl`.

**Comment by mhesselbarth** [comment]
Is it just me having problems compiling?

**Comment by bitbacchus** [comment]
> Is it just me having problems compiling?

Seems to work on travis and appveyor... What does the compiler say?

**Comment by bitbacchus** [comment]
> hi @bitbacchus , I think we could replace the old function with the new ones. However, I would suggest to test it first my comparing results (and times) of the cclabel functions with `rcpp_ccl`.

Sure, there are only three versions for testing and comparing. In the end, we only need one function :-)

I did some tests on my Laptop, but I didn't find a convenient way to benchmark, because I don't know how to call the old cclabel outside of the package. Do we need a wrapper function for testing purposes here?

I would like to call ccl_4, ccl_8 and ccl_8_old (ccl_4 is still the old version) like so:
```
landscape <- raster::as.matrix(landscapemetrics::augusta_nlcd)
class <- 2
filter_matrix <- matrix(NA,
                        nrow = nrow(landscape),
                        ncol = ncol(landscape))
filter_matrix1[landscape == class] <- 1L

# rcpp_ccl manipulates the matrix in-place
# [] ensures that R sends a deep copy as function parameter
bench::mark(
    landscapemetrics:::rcpp_ccl(filter_matrix[], 4),
    landscapemetrics:::rcpp_ccl(filter_matrix[], 8)
)

  expression                                         min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc
  <bch:expr>                                      <bch:> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>
1 landscapemetrics:::rcpp_ccl(filter_matrix[], 4) 1.65ms 1.74ms      489.    2.28MB     34.4   185    13
2 landscapemetrics:::rcpp_ccl(filter_matrix[], 8) 1.65ms 1.75ms      446.    2.28MB     42.5   168    16
```

**Comment by mhesselbarth** [comment]
> Seems to work on travis and appveyor... What does the compiler say?

Something with that some objects are protected members of std::

Travis and Appveyor only test Windows and Linux, right? Might be an issue with macOS then?

**Comment by bitbacchus** [comment]
OK, here is the way to go for benchmarking and testing:

```
# R CMD SHLIB ./src/cclabel_8.c
# R CMD SHLIB ./src/cclabel_4.c
dyn.load("./src/cclabel_8.so") # .dll for Windows
dyn.load("./src/cclabel_4.so") # .dll for Windows

res <- bench::mark(
    rcpp_4 = landscapemetrics:::rcpp_ccl(filter_matrix[], 4),
    rcpp_8 = landscapemetrics:::rcpp_ccl(filter_matrix[], 8),
    ccl_8 = .Call('ccl_8', filter_matrix[]),
    ccl_4_old = .Call('ccl_4', filter_matrix[]),
    ccl_8_old = .Call('ccl_8_old', filter_matrix[]), check = FALSE
)
> res
# A tibble: 5 x 13
  expression      min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result                  memory           time     gc                
  <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>                  <list>           <list>   <list>            
1 rcpp_4       1.67ms    1.8ms      480.    2.28MB     46.4   176    17      367ms <NULL>                  <df[,3] [3 × 3]> <bch:tm> <tibble [193 × 3]>
2 rcpp_8       1.67ms   1.88ms      454.    2.28MB     40.8   167    15      368ms <NULL>                  <df[,3] [3 × 3]> <bch:tm> <tibble [182 × 3]>
3 ccl_8        1.35ms   1.51ms      617.    3.42MB     91.9   188    28      305ms <int[,679] [440 × 679]> <df[,3] [3 × 3]> <bch:tm> <tibble [216 × 3]>
4 ccl_4_old    2.24ms   2.78ms      330.    3.42MB     29.4   101     9      306ms <int[,679] [440 × 679]> <df[,3] [3 × 3]> <bch:tm> <tibble [110 × 3]>
5 ccl_8_old    2.24ms   2.37ms      386.    3.42MB     44.7   147    17      380ms <int[,679] [440 × 679]> <df[,3] [3 × 3]> <bch:tm> <tibble [164 × 3]>
```

**Comment by bitbacchus** [comment]
> > Seems to work on travis and appveyor... What does the compiler say?
> 
> Something with that some objects are protected members of std::
> 
> Travis and Appveyor only test Windows and Linux, right? Might be an issue with macOS then?

Yes, or clang... But it's kinda weird...
Do you have gcc installed? Just to check?

**Comment by mhesselbarth** [comment]
I just double-checked and yes gcc is installed

**Comment by Nowosad** [comment]
> OK, here is the way to go for benchmarking and testing:
> 
> ```
> # R CMD SHLIB ./src/cclabel_8.c
> # R CMD SHLIB ./src/cclabel_4.c
> dyn.load("./src/cclabel_8.so") # .dll for Windows
> dyn.load("./src/cclabel_4.so") # .dll for Windows
> 
> res <- bench::mark(
>     rcpp_4 = landscapemetrics:::rcpp_ccl(filter_matrix[], 4),
>     rcpp_8 = landscapemetrics:::rcpp_ccl(filter_matrix[], 8),
>     ccl_8 = .Call('ccl_8', filter_matrix[]),
>     ccl_4_old = .Call('ccl_4', filter_matrix[]),
>     ccl_8_old = .Call('ccl_8_old', filter_matrix[]), check = FALSE
> )
> > res
> # A tibble: 5 x 13
>   expression      min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result                  memory           time     gc                
>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>                  <list>           <list>   <list>            
> 1 rcpp_4       1.67ms    1.8ms      480.    2.28MB     46.4   176    17      367ms <NULL>                  <df[,3] [3 × 3]> <bch:tm> <tibble [193 × 3]>
> 2 rcpp_8       1.67ms   1.88ms      454.    2.28MB     40.8   167    15      368ms <NULL>                  <df[,3] [3 × 3]> <bch:tm> <tibble [182 × 3]>
> 3 ccl_8        1.35ms   1.51ms      617.    3.42MB     91.9   188    28      305ms <int[,679] [440 × 679]> <df[,3] [3 × 3]> <bch:tm> <tibble [216 × 3]>
> 4 ccl_4_old    2.24ms   2.78ms      330.    3.42MB     29.4   101     9      306ms <int[,679] [440 × 679]> <df[,3] [3 × 3]> <bch:tm> <tibble [110 × 3]>
> 5 ccl_8_old    2.24ms   2.37ms      386.    3.42MB     44.7   147    17      380ms <int[,679] [440 × 679]> <df[,3] [3 × 3]> <bch:tm> <tibble [164 × 3]>
> ```

@bitbacchus are the results of the old and the new code identical?

**Comment by mhesselbarth** [comment]
Okay...I googled a bit and it seems like including `#include <array>`in the header `rcpp_cclabel.h` fixes the problem and I can compile. 

Does this somehow screw up something else @bitbacchus?  Never sure with your dark C++ voodoo magic :)

```
#ifndef CCLABEL_H
#define CCLABEL_H

#include "Rcpp.h"
#include <array>

using namespace Rcpp;

void rcpp_ccl(IntegerMatrix mat, int directions = 8);

#endif // CCLABEL_H
```

**Comment by bitbacchus** [comment]
> @bitbacchus are the results of the old and the new code identical?

Yes, for the new ccl_8 code. But the Rcpp code uses a different algorithm, therefore their results are not identical, but equivalent:

current algorithm:
ccl_old
new algorithm:
rcpp

**Comment by bitbacchus** [comment]
> Does this somehow screw up something else @bitbacchus? Never sure with your dark C++ voodoo magic :)

No, the <array> doesn't hurt. I just would prefer to have it in the .cpp file, though.

**Comment by Nowosad** [comment]
@bitbacchus 
1. Have you changes 4-connection as well?
2. I think it is a rather large change. This makes impossible to exactly reproduce results from the previous versions of landscapemetrics. Would it be possible to achieve the same order as in the older implementation?

**Comment by mhesselbarth** [comment]
> @bitbacchus
> 
> 1. Have you tested 4-connection as well?
> 2. I think it is a rather large change. This makes impossible to exactly reproduce results from the previous versions of landscapemetrics. Would it be possible to achieve the same order as in the older implementation?

I agree that this might be a rather big change, however, maybe one worth considering. 

There are several advantages: 
1. We rely only on Rcpp and not a mixture of Rcpp and C (as currently).
2. We would get rid of the contribution of the authors of the CCL function (well not an important point but still).
2. I did some benchmarking and the speed of the functions seems to be more or less similar, however, the RAM requirement of the Rcpp function is lower. However, I only checked for small landscapes and not large ones, yet. 
3. Is the different numbering of patches really that important? On class and landscape level results will be identical anyways. On patch level the results stay the same, only the patch id changes (i.e. the area of largest patch is the same it will be only e.g. id 3 instead of 25).

**Comment by Nowosad** [comment]
Hi @mhesselbarth ,
just to be clear - I am not against the changes. I just think it would be great if we could have the same numbering in the new version. If not, we probably should add the information about this change in several places (e.g., NEWS, twitter, etc.)

**Comment by mhesselbarth** [comment]
And seems like speed and RAM improvments seem to increase for larger landscapes

**Comment by bitbacchus** [comment]
@Nowosad 
> 1. Have you tested 4-connection as well?

Yes, but there is no new ccl_4 version, yet. I'd make one if necessary.

> 2. I think it is a rather large change. This makes impossible to exactly reproduce results from the previous versions of landscapemetrics. Would it be possible to achieve the same order as in the older implementation?

Yes, I agree. But there is no (sane) way to have the labels identical, as the algorithms work fundamentally different.

**Comment by bitbacchus** [comment]
> And seems like speed and RAM improvments seem to increase for larger landscapes

I chose the algorithm for two reasons:
1. simple to understand and easy to code
2. low RAM requirements, linear scaling

There are some faster algorithms out there but they are more complicated and need more RAM and RAM demand does not scale linearly with landscape size.

**Comment by Nowosad** [comment]
Just out of curiosity - @bitbacchus where do you look for algorithms?

**Comment by bitbacchus** [comment]
> Just out of curiosity - @bitbacchus where do you look for algorithms?

http://imagelab.ing.unimore.it/imagelab/pubblicazioni/2016-icpr-yacclab.pdf
https://elib.dlr.de/100363/1/published_version.pdf
and, of course
https://en.wikipedia.org/wiki/Connected-component_labeling (here I have the actual algorithm from)

**Comment by bitbacchus** [comment]
> > Just out of curiosity - @bitbacchus where do you look for algorithms?
> 
> http://imagelab.ing.unimore.it/imagelab/pubblicazioni/2016-icpr-yacclab.pdf
> https://elib.dlr.de/100363/1/published_version.pdf
> and, of course
> https://en.wikipedia.org/wiki/Connected-component_labeling (here I have the actual algorithm from)

Ah, or do you mean in general? Actually Wikipedia is quite good, once you know the algorithm's name, then there is http://www.rosettacode.org and http://numerical.recipes/

**Comment by mhesselbarth** [comment]
Okay...so what are our final thoughts about the new connected labeling? I would vote for using @bitbacchus 's new one, even though the patch IDs change (and announce that in the news, homepage, etc).

**Comment by Nowosad** [comment]
@mhesselbarth fine with me.

**Pull request merged**
