### PR TITLE
Adds lsm_l_relmutinf

### PR DESCRIPTION
**Pull request by Nowosad**
@mhesselbarth please take a look at it and let me know if I am missing anything

### CODE REVIEW

**Comment by mhesselbarth** [comment]
Looks good to me. Only tests are missing.

**Comment by Nowosad** [comment]
@mhesselbarth - so true. I will add some tests and let you know.

**Comment by Nowosad** [comment]
Done. @mhesselbarth feel free to merge it.

**Comment by mhesselbarth** [comment]
Awesome! Will be part of the next update (roughly beginning of Sep)

**Pull request merged**
